sudo: required
language: cpp

compiler:  
  - g++

    
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository ppa:kubuntu-ppa/backports -y
  - sudo apt-get update -qq
  - sudo apt-get install --only-upgrade cmake

install:
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  
before_script:  
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE:STRING=release

script: make && make test