language: cpp

compiler:  
    - gcc
    - clang
    
before_install:
  - sudo add-apt-repository ppa:kubuntu-ppa/backports -y
  - sudo apt-get update -qq
  - sudo apt-get install --only-upgrade cmake

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: make && make test

os:
  - linux
  - osx
