sudo: required
language: cpp

compiler:  
  - gcc
  - clang
    
before_install:
  - sudo add-apt-repository ppa:kubuntu-ppa/backports -y
  - sudo apt-get update -qq
  - sudo apt-get install --only-upgrade cmake

install:
  - echo "$CXX"
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ "$CXX" = "g++" ]; then export CMAKE_FORCE_OPTIONS_FOR="GCC"; fi
  - if [ "$CXX" = "clang" ]; then export CMAKE_FORCE_OPTIONS_FOR="Clang"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
  
before_script:  
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE:STRING=release

script: make && make test

os:
  - linux
  - osx
